### ISSUE TITLE
ERROR DROP EVENT remove_unpaid_bookings

### ISSUE THREAD

**Issue by wes45** [hschiebold/ep3-bs#10]
If I run this SQL-query in the database by using phpMyAdmin

DROP EVENT remove_unpaid_bookings;
SET GLOBAL event_scheduler = ON;
CREATE EVENT remove_unpaid_bookings ON SCHEDULE EVERY 10 MINUTE STARTS '2019-11-14 00:00:00' ON COMPLETION PRESERVE DO delete from bs_bookings where `status` = 'single' and `status_billing` = 'pending' and created < (NOW() - INTERVAL 3 HOUR) and bid in (select bid from bs_bookings_meta where `key` = 'directpay' and `value` = 'true');

the result is: 

ERROR
DROP EVENT remove_unpaid_bookings
MySQL : 
#1539 - Unknown event 'remove_unpaid_bookings'

Could you please let me know what I am doing wrong here?

**Comment by hschiebold** [comment]
then only these 2 sql commands and update the date : 

SET GLOBAL event_scheduler = ON;


CREATE EVENT remove_unpaid_bookings ON SCHEDULE EVERY 10 MINUTE STARTS '2019-11-14 00:00:00' ON COMPLETION PRESERVE DO delete from bs_bookings where status = 'single' and status_billing = 'pending' and created < (NOW() - INTERVAL 3 HOUR) and bid in (select bid from bs_bookings_meta where key = 'directpay' and value = 'true');

**Comment by wes45** [comment]
I get error for line 1;

Error
    Expression missing. (near "ON" at position 29)

**Comment by wes45** [comment]
problem solved, it was bad copy_paste of the code from this thread
