### ISSUE TITLE
payment not working

### ISSUE THREAD

**Issue by rrdsgn** [hschiebold/ep3-bs#11]
i have problem setting up the local.php
after configuring everything I am getting this error:

> Fatal error: Uncaught Error: Class 'Payum\Stripe\KlarnaCheckoutGatewayFactory' not found in /html/buchungssystem/config/autoload/local.php:72 Stack trace: #0 /html/buchungssystem/vendor/zendframework/zend-config/src/Factory.php(110): include() #1 /html/buchungssystem/vendor/zendframework/zend-modulemanager/src/Listener/ConfigListener.php(365): Zend\Config\Factory::fromFile('config/autoload...') #2 /html/buchungssystem/vendor/zendframework/zend-modulemanager/src/Listener/ConfigListener.php(141): Zend\ModuleManager\Listener\ConfigListener->addConfigByPath('config/autoload...', 'glob_path') #3 [internal function]: Zend\ModuleManager\Listener\ConfigListener->onMergeConfig(Object(Zend\ModuleManager\ModuleEvent)) #4 /html/buchungssystem/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent)) #5 /html/buchungssystem/vendor/zendframework/zend-eventmanager/src/EventManager.php(248): Zend\EventManager\EventManager->triggerListeners('mergeConfig', Object(Zend\Mo in /html/buchungssystem/config/autoload/local.php on line 72

if I delete the Klarna Checkout everything seems to be fine:

>   'klarna_checkout' => (new \Payum\Stripe\KlarnaCheckoutGatewayFactory())->create(array(
                'secret' => '?',
                'merchant_id' => '?',
                'sandbox' => true
            )),

Then I am trying to book.. I am getting the popup where to choose the payment method (stripe logo is missing there).
I tried PayPal and stripe. With paypal I am getting Error 404 - Page not found. With stripe I am getting the payment page (seems there is missing the style sheet), after entering the cc card details I am getting also a 404 error.

**Comment by hschiebold** [comment]
Do you have the complete vendor path from my instance as described in the README?

Can you paste your local and project config please? (clearing your secrets before)

**Comment by rrdsgn** [comment]
yes I have the complete vendor path. Here are the settings:

> 
/**
 * Local application configuration
 *
 * Insert your local database credentials here
 * and provide the email address the system should use.
 */

$detailsClass = 'Application\Model\PaymentDetails';

$project_config = require 'config/autoload/project.php';

return array_merge($project_config, array(
    'db' => array(
        'database' => '',
        'username' => '',
        'password' => '',

        'hostname' => '',
        'port' => null,
    ),
    'mail' => array(
        'type' => 'sendmail', // or 'smtp' or 'smtp-tls'
        'address' => '',
            // Make sure 'bookings.example.com' matches the hosting domain when using type 'sendmail'

        'host' => '', // for 'smtp' type only, otherwise remove or leave as is
        'user' => '', // for 'smtp' type only, otherwise remove or leave as is
        'pw' => '', // for 'smtp' type only, otherwise remove or leave as is

        'port' => 'auto', // for 'smtp' type only, otherwise remove or leave as is
        'auth' => 'plain', // for 'smtp' type only, change this to 'login' if you have problems with SMTP authentication
    ),
    'i18n' => array(
        'choice' => array(
            'en-US' => 'English',
            'de-DE' => 'Deutsch',

            // More possible languages:
            // 'fr-FR' => 'Français',
            // 'hu-HU' => 'Magyar',
        ),

        'currency' => 'EUR',

        // The language is usually detected from the user's web browser.
        // If it cannot be detected automatically and there is no cookie from a manual language selection,
        // the following locale will be used as the default "fallback":
        'locale' => 'de-DE',
    ),
    'payum' => array(
        'token_storage' => new \Payum\Core\Storage\FilesystemStorage(
            __DIR__.'/../../data/payum',
            'Application\Model\PaymentSecurityToken',
            'hash'
        ),
        'gateways' => array(
            'paypal_ec' => (new \Payum\Paypal\ExpressCheckout\Nvp\PaypalExpressCheckoutGatewayFactory())->create(array(
                'username' => '',
                'password' => '',
                'signature' => '',
                'sandbox' => false
            )),
            'stripe' => (new \Payum\Stripe\StripeCheckoutGatewayFactory())->create(array(
                'publishable_key' => '',
                'secret_key' => '',
                'sca_flow' => true,
                'payum.template.obtain_token' => '@PayumStripe/Action/stripe_js.html.twig',
                'payum.template.require_confirmation' => '@PayumStripe/Action/stripe_confirm.html.twig'
            )),
            

        ),
        'storages' => array(
            $detailsClass => new \Payum\Core\Storage\FilesystemStorage(__DIR__.'/../../data/payum', $detailsClass, 'id'),
        )
    ),
));


>


$instance = 'buchungssystem';

return array(
    // basepath of the instance on your server - i.e. tvas-booking-dev for https://tennis-rudolstadt.de/tvas-booking-dev or '' if you don't have a basepath square/ i.e. 
    'basepath' => $instance,
    // origin url of your server - http://yourip - if  you don't have a proxy, baseurl and proxyurl should be the same like https://tennis-rudolstadt.de
    'baseurl' => '',
    // the proxy url - i.e. https://tennis-rudolstadt.de
    'proxyurl' => '',
    'cookie_config' => array(
        'cookie_name_prefix' => $instance,
    ),
    'redirect_config' => array(
        'cookie_name' => $instance.'-origin',
        'default_origin' => 'frontend',
    ),
    'session_config' => array(
        'name' => $instance.'-session',
        'save_path' => getcwd() . '/data/session/',
        'use_cookies' => true,
        'use_only_cookies' => true,
    ),
    'genDoorCode' => false,
    'doorCodeTimeBuffer' => '15 minutes',
    // API http request for your door system
    'doorCodeRequest' => '?',
    // show a flash message where you can manually book if you disable all payment methods 
    'tmpBookingAt' => '?',
    // enable/disable specific payment providers 
    'paypal' => true,
    'stripe' => true,
    // enable/disable stripe payment methods (possible values: card, sepa_debit, ideal, giropay)
    'stripePaymentMethods' => array(
        'card'
    ),
    // enable/disable stripe PaymentRequest (pmr) API for apple / google pay  
    'stripePaymentRequest' => 'true',
    // select the suitable icon for the selected stripe payment methods from imgs-client/layout/stripe_icons  
    'stripeIcon' => 'card.png',
    // select a default method 
    'stripeDefaultPaymentMethod' => 'card',
    // some payment methods require a confirmation process - select if you want to automate the click on 'authorize' and 'confirm' button
    'stripeAutoConfirm' => 'false',
    // stripe webhook secret for update of pending PaymentIntents / not yet fully implemented
    'stripeWebhookSecret' => '',
    // not yet fully implemented
    'klarna' => false,
    // classic behaviour of ep3-bs with booking on bill 
    'billing' => false,
    // select which payment provider should be activated as default 
    'payment_default' => 'paypal',
);

I guess I found the problem in project.php

if I change this:

> $instance = 'buchungssystem';

to this:

> $instance = 'buchungssystem/public';

it seems to work fine. I guess this happens because of a wrong .htaccess config? 
but I wonder why I have to delete the klarna section to make it work.

**Comment by rrdsgn** [comment]
is it possible to change the time until unpaid bookings get removed?

**Comment by hschiebold** [comment]
"if I change this:

    $instance = 'buchungssystem';

to this:

    $instance = 'buchungssystem/public';

it seems to work fine. I guess this happens because of a wrong .htaccess config?
but I wonder why I have to delete the klarna section to make it work."

yes - if you don't point your webroot to the public dir directly as described in the original project - you have to point her to "somewhat/public"

**Comment by hschiebold** [comment]
the klarna thing is mine - somehow i checked in the wrong path to the Klarna Gateway in the dist file - it has to be \Payum\Klarna\Checkout\KlarnaCheckoutGatewayFactory

**Comment by hschiebold** [comment]
just updated the git

**Comment by hschiebold** [comment]
if you was it today with the TEST bookings on our production system - than please use the dev environment (https://tennis-rudolstadt.de/tvas-booking-dev/public/) - not the production

**Comment by hschiebold** [comment]
> 
> 
> is it possible to change the time until unpaid bookings get removed?

Do you mean the  3 hours delay ? This is done via the SQL event described in the README. There the "INTERVAL 3 HOUR" segment in the SQL statement. This is the lifetime of a paypal token - and it is possible that the fullfillment of the payment process of paypal can have this delay. So if you set this to 1 hour - the booking will be canceled in the app but the payment can be fullfilled after 2 hours

**Comment by rrdsgn** [comment]
> if you was it today with the TEST bookings on our production system - than please use the dev environment (https://tennis-rudolstadt.de/tvas-booking-dev/public/) - not the production

i am sorry for that.

**Comment by hschiebold** [comment]
> ```
> $instance = 'buchungssystem/public';
> ```

it is better to set the basepath to $instance."/public" and leave the instance as  'buchungssystem'
otherwise you have a bit strange session names

**Comment by rrdsgn** [comment]
> "if I change this:
> 
> ```
> $instance = 'buchungssystem';
> ```
> 
> to this:
> 
> ```
> $instance = 'buchungssystem/public';
> ```
> 
> it seems to work fine. I guess this happens because of a wrong .htaccess config?
> but I wonder why I have to delete the klarna section to make it work."
> 
> yes - if you don't point your webroot to the public dir directly as described in the original project - you have to point her to "somewhat/public"

can you please tell me how to point the webroot 

> > ```
> > $instance = 'buchungssystem/public';
> > ```
> 
> 
> it is better to set the basepath to $instance."/public" and leave the instance as  'buchungssystem'
> 
> otherwise you have a bit strange session names

perfect. Thank you very much. Thats the perfect solution.

**Comment by rrdsgn** [comment]
> > is it possible to change the time until unpaid bookings get removed?
> 
> Do you mean the 3 hours delay ? This is done via the SQL event described in the README. There the "INTERVAL 3 HOUR" segment in the SQL statement. This is the lifetime of a paypal token - and it is possible that the fullfillment of the payment process of paypal can have this delay. So if you set this to 1 hour - the booking will be canceled in the app but the payment can be fullfilled after 2 hours

yes. should i add this to SQL? Or is this being done at setup?

> DROP EVENT remove_unpaid_bookings;
SET GLOBAL event_scheduler = ON;
CREATE EVENT remove_unpaid_bookings ON SCHEDULE EVERY 10 MINUTE STARTS '2019-11-14 00:00:00' ON COMPLETION PRESERVE DO delete from bs_bookings where `status` = 'single' and `status_billing` = 'pending' and created < (NOW() - INTERVAL 3 HOUR) and bid in (select bid from bs_bookings_meta where `key` = 'directpay' and `value` = 'true');

**Comment by hschiebold** [comment]
> can you please tell me how to point the webroot

with the DocumentRoot option in a separate vhost maybe 

i have to do it by myself as you noticed

**Comment by hschiebold** [comment]
> yes. should i add this to SQL? Or is this being done at setup?
> 
> > DROP EVENT remove_unpaid_bookings;
> > SET GLOBAL event_scheduler = ON;
> > CREATE EVENT remove_unpaid_bookings ON SCHEDULE EVERY 10 MINUTE STARTS '2019-11-14 00:00:00' ON COMPLETION PRESERVE DO delete from bs_bookings where `status` = 'single' and `status_billing` = 'pending' and created < (NOW() - INTERVAL 3 HOUR) and bid in (select bid from bs_bookings_meta where `key` = 'directpay' and `value` = 'true');

no there is no setup action for that - you have to manually use this SQL in your mysql db

**Comment by rrdsgn** [comment]
ok perfect. Thank you very much.

**Comment by hschiebold** [comment]
can we close the issue?

**Comment by rrdsgn** [comment]
yes thank you. working fine now.
