### ISSUE TITLE
zusätzliche Checkbox als Zahlungsoption

### ISSUE THREAD

**Issue by murreni** [hschiebold/ep3-bs#12]
Hallo,

ist es möglich, eine weitere Checkbox in diesem Fenster zu installieren mit Bild/Text: "Ich bin Mitglied und buche einen Freiplatz", oder so ähnlich?
![grafik](https://user-images.githubusercontent.com/14903548/115204855-3e73a800-a0f9-11eb-90d5-5e1f165d6b6d.png)

Hintergrund: 
Mitglieder müssen den Platz ja nicht bezahlen. Gäste schon! Ich könnte den Mitgliedern nun schreiben, dass sie bitte die Checkbox "Rechnung" auswählen sollen, wir dann aber keine Rechnung stellen. Ist unschön. Mit einer zusätzlichen Checkbox würde das mehr hermachen.

Danke und Gruß
Murreni

**Comment by hschiebold** [comment]
Hallo, 

in meiner Entwicklungsversion gibt es derzeit bereits die Möglichkeit in der Verwaltung einen Nutzer als Vereinsmitglied zu deklarieren. (durch diejenigen mit der entsprechenden Rolle, bei uns Vorstand und ich - einfach Häkchen setzen bei Mitgliedern) Wir brauchen eine solche Funktionalität, da wir bestimmte Zeiten bei der Buchung der Halle für Vereinsmitglieder reservieren wollen.

Zusätzlich kommt demnächst unterschiedliche Preise für Mitglieder und Nichtmitglieder. Allein schon wegen der unterschiedlichen Mehrwertsteuer normalerweise notwendig.

Auf dieser Basis könnte man nun das Ganze so erweitern, dass man bei einem Platz im backend einstellen kann, ob der für Mitglieder überhaupt etwas kostet oder nicht.

Wie wärs damit?

**Comment by hschiebold** [comment]
Macht aber nur Sinn, wenn man Freiplatz und Halle auch wirklich dediziert deklariert in der App. Anders funktioniert es ja verwaltungstechnisch auch nicht wirklich.

**Comment by hschiebold** [comment]
Wie schnell bräuchtet Ihr denn sowas? Bin ein bisschen ausgelastet zur Zeit.

**Comment by murreni** [comment]
Ja, genaus so etwas wäre ideal. 
Mach dir kein Stress ist nicht dringend! 
Falls es zukünftig Berücksichtigung findet, wäre natürlich perfekt :-)

Viele Grüße

**Comment by hschiebold** [comment]
Habs mal initial in meiner dev Version so umgesetzt. Noch ziemlich frisch und ungetestet. Hab mal Platz "Halle" angelegt mit im backend eingestellten Preisen von 30 für externe und 20 für Mitglieder plus gültige Mehrwertsteuer. Platz "Kunstrasen" kostet nix für Mitglieder - für Externe 10.

Wenn du magst kannst du ja mal zuerst als Externer testen und dann  setz ich dich mal auf Mitglied.

https://tennis-rudolstadt.de/tvas-booking-dev

Gruß Holger

**Comment by murreni** [comment]
TipTop, 
klappt einwandfrei als Externer.
Switch mich mal bitte auf Mitglied :-)

Gruß
Franky

**Comment by hschiebold** [comment]
Hab dich grad zum Mitglied erklärt

**Comment by murreni** [comment]
Habs schon getestet. Genial 👍 
auch die Funktion, dass Mitglieder reservierte Vereinstunden buchen können ist spitzenklasse.

**Comment by hschiebold** [comment]
Ich werde meinen aktuellen Code stand nochmal reviewen. Ich war da noch an 1,2 Erweiterungen dran, hab das aber aus Zeitmangel liegen lassen. Dann schau ich mal ob ich mit der 1.7 er von Tobias morgen kann, damit man mal PHP auf 7.4 anheben kann und check es ein die Tage - hoffe ich.

**Comment by hschiebold** [comment]
<img width="282" alt="Mitglied" src="https://user-images.githubusercontent.com/18187605/115836054-50b25680-a417-11eb-8cd5-86b6bdb8b084.PNG">

**Comment by hschiebold** [comment]
<img width="970" alt="Preise" src="https://user-images.githubusercontent.com/18187605/115836095-5c9e1880-a417-11eb-977d-62a44bee3d72.PNG">

**Comment by hschiebold** [comment]
Im Backend sieht das dann so aus.

**Comment by hschiebold** [comment]
<img width="770" alt="Verhalten" src="https://user-images.githubusercontent.com/18187605/115836532-e221c880-a417-11eb-8435-89c241f4ad14.PNG">

**Comment by hschiebold** [comment]
<img width="584" alt="Platz" src="https://user-images.githubusercontent.com/18187605/115836580-eea62100-a417-11eb-9a3b-8cf7a355e6a3.PNG">

**Comment by hschiebold** [comment]
<img width="583" alt="Kunstrasen" src="https://user-images.githubusercontent.com/18187605/115836599-f4036b80-a417-11eb-9121-b6c0d1fbd229.PNG">

**Comment by hschiebold** [comment]
Um bestimmte Tag und Uhrzeiten für die Vereinsmitglieder zu reservieren im backend im Bereich Verhalten erst die Tage definieren. Je Platz kann das dann wieter mit Uhrzeiten eingeschränkt oder wieder aufgehoben werden wie beim Kunstrasen. 

Wir haben nur eine Einfeldhalle und zu Zeiten wo wir die noch benutzen durften ;-) haben dann gerade am WE schon zu viele Externe gebucht,  so dass wir diese Zeiten für die Mitglieder reservieren wollten.

**Comment by murreni** [comment]
Super, freu mich schon es zu installieren :-)
Vielen, vielen Dank.
Grüße
Franky

> 
> Ich werde meinen aktuellen Code stand nochmal reviewen. Ich war da noch an 1,2 Erweiterungen dran, hab das aber aus Zeitmangel liegen lassen. Dann schau ich mal ob ich mit der 1.7 er von Tobias morgen kann, damit man mal PHP auf 7.4 anheben kann und check es ein die Tage - hoffe ich.
> […](#)
> Am 22.04.2021 um 20:40 schrieb murreni ***@***.***>: ﻿ Habs schon getestet. Genial 👍 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by murreni** [comment]
Hallo Holger,

gibt es schon Neuigkeiten wann du die Anpassungen veröffentlichst?

Danke und viele Grüße

**Comment by hschiebold** [comment]
Oh sorry, das hab ich völlig vergessen / verdrängt 😞 mach die Woche mal.

**Comment by hschiebold** [comment]
Ich habe den code Stand, dr mir auf der dev gerade läuft eben eingecheckt. Er ist noch nicht wie oben geschrien mit der letzten Version von Tobias gemerged. Dazu hatt eich schlicht noch keine Zeit gefunden. Ich denke du kannst mit diesem code Stand arbeiten. Mach aber auf jeden Fall eine Sicherung deiner bisherigen Instanz. 

Meld dich hier, wenn noch was fehlen sollten / nicht funktionieren sollte. 

Gruß Holger

**Comment by murreni** [comment]
Super, vielen Dank. Habe es auch schon installiert. 
Allerdings erscheint folgende Fehlermeldung, sobald ich Preise bzw. neue Regel einstellen will:
![grafik](https://user-images.githubusercontent.com/14903548/121584870-3d446480-ca32-11eb-857a-bf282e543a67.png)


Kannst du damit was anfangen?

Grüße
Franky

**Comment by murreni** [comment]
habs hinbekommen. :-)
Musste in der sql Datenbank bei bs_square_pricing ein neues Feld "member" hinzufügen. Der Eintrag wird anscheinend beim setup nicht miterstellt.

**Comment by hschiebold** [comment]
Ich wusste irgendwie ich hab was vergessen 😉 ich mach das mal noch als Hinweis in die read me , ich wollt an Tobias Setup eigentlich nix rumfummeln

**Comment by hschiebold** [comment]
ich hab die 2 statements, welche die DB erweitern in meinem fork, jetzt mit in die ep3bs.sql am Ende

**Comment by murreni** [comment]
Hi Holger,
hab jetzt mal alles getestet und es läuft wunderbar :-) 
Vielen, vielen Dank!
Eine Frage habe ich aber noch:
Gibt es eine Möglichkeit, die Gastspieler nur einen bestimmten Platz buchen zu lassen?
Entweder, dass sie nur den einen Platz in der Übersicht sehen können oder aber bei Buchung des "falschen Platzes" die Meldung kommt: "Dieser Platz ist Mitgliedern vorbehalten, bitte buchen sie Platz 5"

Grüße
Franky

**Comment by hschiebold** [comment]
Derzeit nur indem du die anderen Plätze 1-4 für den Verein über Vereinsreservierte Zeiten deklarierst. Siehe in meiner dev Version am WE 14-20 Uhr derzeit für Platz Halle. Due deklarierest einfach den kompletten Zeitraum von Platz 1-4 für den Verein.

**Comment by murreni** [comment]
Ahh, ok. Verstehe.
Habe nun unter "Platzeigenschaften" die Vereinszeit festgelegt
und unter "Verhalten" die Tage. Allerding scheint da was nicht zu klappen. Sobald ich Datum/Tag eingebe sehe ich folgendes in der Übersicht:
![grafik](https://user-images.githubusercontent.com/14903548/121729263-8c4fcf80-caee-11eb-85d0-fef49720507c.png)

Hast du eine Idee?

**Comment by murreni** [comment]
Den DateTime Fehler konnte ich beheben, indem ich in der Cell.php in Line 123 und 124 jeweils ein "(int)" vor die Parameter eingefügt habe (und jetzt werden auch die Vereinsstunden in den squares angezeigt):
![grafik](https://user-images.githubusercontent.com/14903548/121769625-f2773980-cb64-11eb-8bd2-7e630833feb2.png)

Der Offset Fehler verbleibt allerdings noch:
![grafik](https://user-images.githubusercontent.com/14903548/121769648-176bac80-cb65-11eb-8589-1d6b4c3c8d9d.png)

**Comment by murreni** [comment]
Auch den Offset Fehler habe ich nun wegbekommen. Hier die Änderungen:
![grafik](https://user-images.githubusercontent.com/14903548/121770688-0f167000-cb6b-11eb-9e82-ff294f8a6d6a.png)

**Comment by murreni** [comment]
Der gleiche Fehler tritt dann bei Gastbuchung nochmals an anderen Stellen auf:
/module/Square/src/Square/Service/SquareValidator.php
![grafik](https://user-images.githubusercontent.com/14903548/121771112-a41a6880-cb6d-11eb-84a4-602abdd1aec7.png)

/module/Square/src/Square/View/Helper/TimeBlockChoice.php
![grafik](https://user-images.githubusercontent.com/14903548/121771169-05dad280-cb6e-11eb-8e9c-ed6ccec47df1.png)

**Comment by murreni** [comment]
Hallo Holger,

kurze Frage. Ich versuche gerade auf der Hilfeseite ein Bild zu platzieren, welches ich zuvor im Filemanager hochgeladen habe:
![grafik](https://user-images.githubusercontent.com/14903548/115761177-5ae63d80-a3a2-11eb-8c63-57fd43c48661.png)

Dies klappt aber leider nicht, da versucht wird folgende Seite aufzurufen **meinedomain.devendor**, statt **meinedomain.de/vendor**

Hast du eine Idee, wo ich da die Anpassung machen muss, damit der Linkaufruf klappt?

Vielen Dank und Grüße
Franky

**Comment by hschiebold** [comment]
Ne sorry, sowas mach ich direkt auf dem Server

**Comment by hschiebold** [comment]
War grad paar Tage im Urlaub. Bei meiner Instanz sind diese Fehler nicht aufgetreten. Wenn ich morgen Zeit finde, schau ich mal in den Code.

**Comment by murreni** [comment]
Hatte ich auch versucht aber irgendwie klappt das nicht. Habe das Bild per ftp nach **/docs-client/upload/1.jpg** verschoben und wollte dann bei Bild einfügen/bearbeiten (siehe Bild oben) unter "Quelle" den Pfad eintragen. Aber das Bild bleibt leer. Auf meiner alten Prod-Instanz klappt das.
 
Ziehe mir das Bild nun testweise über mein bisheriges BS und hinterlege dazu im Quellcode:
**<p><img src="http://pla....**
![grafik](https://user-images.githubusercontent.com/14903548/121798414-7cd3a200-cc26-11eb-87b8-16b526319c60.png)

Ist momentan die einzige Möglichkeit ein Bild in der Hilfe oder Info Seite einzubinden. Ganz komisch!


> 
> Ne sorry, sowas mach ich direkt auf dem Server
> […](#)
> Am 12.06.2021 um 21:33 schrieb murreni ***@***.***>: ﻿ Hallo Holger, kurze Frage. Ich versuche gerade auf der Hilfeseite ein Bild zu platzieren, welches ich zuvor im Filemanager hochgeladen habe: Dies klappt aber leider nicht, da versucht wird folgende Seite aufzurufen meinedomain.devendor, statt meinedomain.de/vendor Hast du eine Idee, wo ich da die Anpassung machen muss, damit der Linkaufruf klappt? Vielen Dank und Grüße murreni — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by murreni** [comment]
Hab jetzt gerade mal die .htaccess, unter **/public/docs-client/upload**, gelöscht und siehe da, ich kann nun den Serverpfad unter "Quelle" eingeben und das Bild wird angezeigt. 

Der Linkaufruf zum Filemanager klappt aber immernoch nicht.

**Comment by hschiebold** [comment]
> 
> 
> Ahh, ok. Verstehe.
> Habe nun unter "Platzeigenschaften" die Vereinszeit festgelegt
> und unter "Verhalten" die Tage. Allerding scheint da was nicht zu klappen. Sobald ich Datum/Tag eingebe sehe ich folgendes in der Übersicht:
> ![grafik](https://user-images.githubusercontent.com/14903548/121729263-8c4fcf80-caee-11eb-85d0-fef49720507c.png)
> 
> Hast du eine Idee?

poste mal bitte deine Einträge in der Verwaltung für die Vereinstage und die Platz Zeiten

**Comment by hschiebold** [comment]
bei mir sieht das so aus bei Verhalten / folgende Tage für den Verein reservieren
Saturday
Sunday
2020-12-07
2020-12-25
2020-12-26

**Comment by hschiebold** [comment]
> 
> 
> Hab jetzt gerade mal die .htaccess, unter **/public/docs-client/upload**, gelöscht und siehe da, ich kann nun den Serverpfad unter "Quelle" eingeben und das Bild wird angezeigt.
> 
> Der Linkaufruf zum Filemanager klappt aber immernoch nicht.

an der .htaccess sowie dem filemanager habe ich meines Erachtens keine Änderungen vorgenommen

**Comment by hschiebold** [comment]
> 
> 
> Hallo Holger,
> 
> kurze Frage. Ich versuche gerade auf der Hilfeseite ein Bild zu platzieren, welches ich zuvor im Filemanager hochgeladen habe:
> ![grafik](https://user-images.githubusercontent.com/14903548/115761177-5ae63d80-a3a2-11eb-8c63-57fd43c48661.png)
> 
> Dies klappt aber leider nicht, da versucht wird folgende Seite aufzurufen **meinedomain.devendor**, statt **meinedomain.de/vendor**
> 
> Hast du eine Idee, wo ich da die Anpassung machen muss, damit der Linkaufruf klappt?
> 
> Vielen Dank und Grüße
> Franky

hab das male eben auf meiner dev Version nachvollzogen - funktioniert problemlos - in meiner Hilfeseite ist grad unten ein Bild drin

**Comment by hschiebold** [comment]
poste mal deine Einträge in der project.php in config - schärze sicherheitsrelevante Einträge

**Comment by hschiebold** [comment]
> 
> 
> bei mir sieht das so aus bei Verhalten / folgende Tage für den Verein reservieren
> Saturday
> Sunday
> 2020-12-07
> 2020-12-25
> 2020-12-26

beim Platz "Kunstrasen" der auch für "Fremde" buchbar sein sool steht 

00:00 in der Vereinsreservierten Uhrzeit 

beim Platz Halle 14:00 bis 20:00

**Comment by hschiebold** [comment]
Ich vermute du hast bei einem Platz da nix als Uhrzeit auswertbares drin stehen

**Comment by hschiebold** [comment]
mit 00:00 bis 00:00 oder 01:00 bis 01:00 oder so ähnlich hebst du die "Vereinseinschränkung" der Tage dann quasi für diesen Platz wieder auf

**Comment by murreni** [comment]
Hi Holger,

mit den oben genannten Anpassungen passt soweit alles und alle Fehlermeldungen sind weg. 
Das mit dem Filemanager ist komisch aber nicht so wichtig, da der Bilderimport ja jetzt, nach .htaccess Löschung, funktioniert.
Eine Frage habe ich aber noch und dann schließe ich den Thread mal :-)
Der SQL Befehl **remove unpaid bookings** funktioniert bei mir nicht, da ich anscheinend nicht die Superrechte in meiner IONOS MySQL DB habe:
_SET GLOBAL event_scheduler = ON
MySQL meldet: Dokumentation
#1227 - Kein Zugriff. Hierfür wird die Berechtigung SUPER benötigt_

Brauche ich dafür dann einen VServer mit Root Rechten, damit ich den SQL Befehl ausführen kann?

**Comment by hschiebold** [comment]
Das geht bestimmt auch anders / kostenlos ;-) 

Es geht ja nur darum aller 3 h die evtl. unbezahlten Buchungen zu löschen. ( trat bei uns sehr selten auf - eher am Anfang als die Leute noch “probiert” haben) 

Um Events im MySQL anzulegen braucht’s wahrscheinlich höhere Rechte, als du gerade hast. 

1) lösch einfach von Hand in der App als Admin die unbezahlten Buchungen 

2) kannst du einen Cron Job auf deinem Server anlegen ? Sollte auf jeden Fall auch mit einfachen User Rechten gehen - dann führst du das Stück SQL in nem cron Job und eben nicht in einem MySQL Event aus

**Comment by murreni** [comment]
Hallo Holger, 

danke für deine Erläuterung. Bisher habe ich das BS auf einem Raspberry Pi betrieben. Da wäre das sicherlich kein Problem mit den Mysql Rechten oder mit dem Cron Job. Die Anforderung vom Vorstand lautet allerdings, das BS auf unserem IONOS (Starter) Webspace, wo auch die Vereins-Homepage liegt, zu installieren. Und ich denke genau da liegt das Problem. Einen Cronjob kann ich mit "IONOS Starter", denke ich mal, nicht einrichten. Aber die VServer sind ja preislich auch nicht so weit weg, von daher die Überlegung.

Gruß
Franky
