### ISSUE TITLE
Buchungsbestätigungsmail

### ISSUE THREAD

**Issue by murreni** [hschiebold/ep3-bs#13]
Hallo Holger,

ich habe nun ein Zusatzprodukt (Gastspieler) erstellt, welches Mitglieder auswählen müssen, die mit einem Gast spielen.
In der Buchungsbestätigungsmail steht aber: Gesamt ->   0,00 € 
Das Zusatzprodukt wurde in der Mail nicht berücksichtigt. Hast du vlt eine schnelle Idee, wie man das anpassen kann, damit man auch die Kosten der Gastbuchung in der Bestätigungsmail sehen kann??

Vielen Dank und Grüße
Franky

**Comment by hschiebold** [comment]
Hmm ich dachte ich hatte das schonmal in nem anderen issue behandelt. Standardmäßig is da nix in den mails. Ich muss mal die anderen issues reviewen. Komm ich aber erst vermutlich die Tage dazu.

**Comment by hschiebold** [comment]
Oh sorry, hier existiert aktuell wohl ein Problem im code Stand in meiner dev Version und damit auch im git. Die Buchungen werden nach der Bezahlung irgendwie nicht richtig aktualisiert. Eigentlich müsste in den Notizen zu einer Buchung auch immer drin stehen wie der payment status ist und womit bezahlt wurde. Das fehlt gerade auf dev. Ebenso scheint eben die Buchung nicht hinsichtlich der zusätzlichen Produkte aktualisiert zu werden und damit fehlt der Posten in der dazugehörigen Rechnung auch im Backend, sowie in der mail. 

is ein bug :-( - hat schonmal funktioniert 

Ich geh mal auf die Suche.

**Comment by hschiebold** [comment]
bitte den Square/src/Square/Controller/BookingController.php aktualisieren  - bug war trivial aber blöd :-( - die Notizen hatte ich kommentiert - sind nicht unbedingt notwendig aber vielleicht trotzdem informativ für die Verwaltung

**Comment by murreni** [comment]
Hallo Holger,
habe ich angepasst aber nun kommt ganz zum Schluss (letzter klick) folgende Fehlermeldung bei Buchung:
![grafik](https://user-images.githubusercontent.com/14903548/124503907-be3f1380-ddc6-11eb-9ede-1b172203ba58.png)

Kannst du damit was anfangen?

**Comment by hschiebold** [comment]
Dann muss ich wohl morgen nochmal im Code schauen und ein paar mehr Tests machen. Bei mir ging es vorhin. Kann aber gut sein aufgrund anderer Bedingungen etc.

**Comment by hschiebold** [comment]
Sorry, mein Bock - Ich hatte natürlich nur eine Buchung mit einem zusätzlichen Produkt für die email getestet. Das ging. Nur ohne zusätzliches Produkt hat den obigen Fehler verursacht. Habs gerade korrgiert und mehrere Fälle durchgetstet.

**Comment by murreni** [comment]
TipTop :-)
Jetzt klappts

Vielen Dank
