### ISSUE TITLE
IBAN speichern

### ISSUE THREAD

**Issue by RaphaelMHa** [hschiebold/ep3-bs#15]
Hallo,

erstmal vielen Dank für die tolle Modifikation des BS. Die Zahlungsmöglichkeit innerhalb des BS war genau das , was wir für unseren Verein gesucht haben. Die Sepa Lastschrift per Stripe funktioniert 1A. Allerdings kam die Frage auf, ob die Möglichkeit besteht, die IBAN irgendwo zu hinterlegen, damit man sie bei Buchung nicht jedes Mal neu eintippen muss. Name und Email werden ja auch in das Buchungsformular übernommen. Gibt es da eine Möglichkeit, auch die IBAN zu übernehmen?

Grüße
Raphael

**Comment by hschiebold** [comment]
Hallo Raphael,

hatte ich selber damals schon dran gedacht und auch damit angefangen. Muss mal schauen wieviel davon ich schon im code gemacht hatte. Wir hatten uns letzlich nur gegen das speichern der jeweiligen IBAN entschieden (Datenschutz, Sicherheit ...) und auch weil wir diese asynchrone Bezahlmöglichkeit nicht weiter forcieren wollten. Bis vor kurzem musste dann noch im stripe dashboard per Hand nachgeschaut werden, ob die Lastschrift auch wirklich erfolgreich gezogen wurde und dann die Buchung per Hand auf bezahlt gesetzt werden in der app. Mittlerweile geht das auch automatisch per webhook von stripe. 

ich schau mal heut Abend oder morgen nach - ich muss jetzt erstmal selber in die Halle zum Training ;-)

Gruß Holger

**Comment by RaphaelMHa** [comment]
Hallo Holger,

super, tausend Dank! 

Das mit dem Stripe Webhook hört sich aber auch interessant an.
Muss ich mal ausprobieren.

Viel Spass beim Training.

Gruß
Raphael

**Comment by hschiebold** [comment]
"Das mit dem Stripe Webhook hört sich aber auch interessant an." kannst du auch mit einer Test Version im stripe dashboard austesten vorher - stripe sendet dann beim event payment_intent.succeded bspw. eine entsprechenden request mit dem payment_intent an den definierten webhook und darin wird dann das Ergebnis ausgewertet und entsprechend die Buchung aktualisiert

**Comment by hschiebold** [comment]
Ich war wohl soweit gekommen, dass der Nutzer die IBAN bei seinen persönlichen Daten speichern konnte.

Todo's  

1) er muss sie auch wieder löschen können - geht noch nicht aufgrund Validierung
2) sie muss im booking Prozess falls vorhanden an den payment Prozess weiter gereicht und an das payment Form übergeben werden
3) dort muss sie dann trotzdem änderbar sein
4) review und sicher stellen, dass auschliesslich der Nutzer selber seine IBAN sieht - evtl IBAN beim speichern zusätzlich verschlüsseln bzw codieren 
5) das ganze feature über die config variabel konfigurierbar machen,  so dass man es administrativ ein und ausschalten kann

Is also noch etwas zu  tun :-(

**Comment by hschiebold** [comment]
UI TODO 2 wird schonmal schwierig bis unmöglich - das war dann wohl auch damals schon der Knackpunkt - man kann über die Stripe JS API, welceh hier für die Forms verwendet wird offenbar die Iban nicht programmatisch setzen - ist nicht erlaubt 

"Uncaught IntegrationError: Sensitive data (like iban) cannot be filled in."

**Comment by RaphaelMHa** [comment]
Alles klar, kein Problem. Wenns nicht geht, gehts nicht

Und wie sieht es mit einem Cookie setzen aus? D.h. wenn man im Formular schon mal händisch die IBAN eingegeben hat, sie beim nächsten mal schon zu Auswahl angezeigt wird. Bin kein Programmierer, von daher entschuldige, falls sowas prinzipiell nicht möglich sein sollte und ich hier dumme Fragen stelle :-) 

Vielen Dank & Grüße
Raphael

**Comment by hschiebold** [comment]
Das Problem ist nicht das Speichern der Iban (ob jetzt per cookie oder anders) - es ist in dem verwendeten worklflow per stripe API nicht erlaubt diese zu setzen. 

Es gibt evtl. eine generischere Alternative von stripe. Man kann den Nutzer samt seine Bezahlmethoden per stripe API speichern und wiederverwenden. Dabei muss der Nutzer seine Bezahlmethode nicht neu definieren. Das schaue ich mir zu rZeit an. Geht nur nicht so schnell. Erfordert wahrscheinlich auch den Umbau des derzeitigen worklflows bei den stripe Methoden und die verwendet payum Bibliothek scheint hier auch noch Bugs zu haben, bzw. veraltet zu sein. 

Wenn ich hier mehr weiss, schreib ich wieder.

**Comment by hschiebold** [comment]
Ich schliesse das mal, da wie beschrieben leider nicht umsetzbar.
