### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by RaphaelMHa** [hschiebold/ep3-bs#16]
Mir ist noch etwas aufgefallen, nachdem ich den aktuellsten Stand neu installiert habe.

PHP 7.4 funktioniert mit der aktuellsten Version deines Forks leider nicht:

**Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /htdocs/Buchungssystem/vendor/zendframework/zend-i18n/src/Translator/Loader/PhpArray.php on line 52** 

`Exception details

Type

    Error

Mitteilung

    __clone method called on non-object

File

    /Buchungssystem/module/Calendar/view/calendar/calendar/index.landscape.phtml:18

Stack trace

    #0 /Buchungssystem/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include()
    #1 /Buchungssystem/vendor/zendframework/zend-view/src/Helper/Partial.php(61): Zend\View\Renderer\PhpRenderer->render(NULL, NULL)
    #2 [internal function]: Zend\View\Helper\Partial->__invoke('calendar/calend...', Array)
    #3 /Buchungssystem/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(Zend\View\Helper\Partial), Array)
    #4 /Buchungssystem/module/Calendar/view/calendar/calendar/index.phtml(14): Zend\View\Renderer\PhpRenderer->__call('partial', Array)
    #5 /Buchungssystem/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('/homepages/14/d...')
    #6 /Buchungssystem/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL)
    #7 /Buchungssystem/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
    #8 /Buchungssystem/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
    #9 /Buchungssystem/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
    #10 /Buchungssystem/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
    #11 /Buchungssystem/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
    #12 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
    #13 /Buchungssystem/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #14 /Buchungssystem/vendor/zendframework/zend-eventmanager/src/EventManager.php(248): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent))
    #15 /Buchungssystem/vendor/zendframework/zend-mvc/src/Application.php(384): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
    #16 /Buchungssystem/vendor/zendframework/zend-mvc/src/Application.php(356): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
    #17 /Buchungssystem/public/index.php(66): Zend\Mvc\Application->run()
    #18 {main}

`

Mit PHP 7.2 erscheint die Meldung nicht.

**Comment by hschiebold** [comment]
Oh, ich hatte letzlich nur meinen fork mal wieder mit der Version von Tobias gemereged und noch gar nicht selber gegen 7.4 getestet. Evtl. müssen da noch andere Pakete aktualisiert werden.

**Comment by hschiebold** [comment]
Tobias hat genau diese Klassen in module/Zend wegen der 7.4 Kompatibilität überschrieben. Nur werden die anscheinend nicht geladen bei dir bzw. die "normalen" aus vendor/... gewinnen. Ich muss mal schauen ob da noch ne config option fehlt. Allerdings habe ich vorhin gesehen, dass es acuh bei den stripe und payum Moulen zu Problemen wegen "array_key_exists" kommen kann. Bis das vollständig unter 7.4 geht muss ich wohl auch selber erst nochmal alles austesten und gegebenenfalls anpassen.

**Comment by hschiebold** [comment]
Man wird den autoloader nochmal aktualisieren müssen, da dieser sich mit der neuen Version von Tobias geändert hat und er damit dafür sorgt, dass die entsprechenden Zend Klassen aus dem module Bereich, welche er überschrieben hat Vorrang haben. 

composer dumpautoload -o

Ich vermute aber , wie oben schon geschrieben, dass noch weitere Updates bezüglich payum und stripe notwendig sind. Da aber hier auch patches meinerseits notwendig waren, müsste ich die erstmal nachziehen, bzw. gegen die neueren Versionen testen.

**Comment by gitroli** [comment]
Hast du vor die Anpassungen für PHP 7.4 in nächster Zeit zu machen oder eher nicht? Mir geht es nur darum, weil dann warte ich noch, ansonsten fange ich an mit deiner Version mal alles aufzusetzen: stripe, Loxone, Licht und Code Touch, ...

**Comment by hschiebold** [comment]
Das ist schlicht eine Zeitfrage, wann ich dazu komme. Ich kann auch noch nicht richtig einschätzen wieviel aufwand das für die stripe und payum Module kostet. wird wohl noch ein paar Wochen dauern.

**Comment by gitroli** [comment]
ok danke für die info

**Comment by gitroli** [comment]
Hat sich hier schon was getan?

**Comment by hschiebold** [comment]
Leider nein. Größeres dringendes Projekt auf Arbeit läuft noch. Ich wollte mittlerweile auf das Upgrade für die 8er Version von Tobias warten, damit ich das dann nicht alles doppelt machen muss. Mit 8 sollten wir dann hoffentlich ne Weile safe seien.

**Comment by gitroli** [comment]
Das ist ein guter Vorschlag, 7.4 soll ja November EOL sein.

**Comment by RaphaelMHa** [comment]
Hallo Holger,

vielen Dank für deine Mühe und die Anpassungen, die du in den letzten Tagen eingestellt hast. 
Hast du evtl. auch schon eine Idee, wann das PHP Update für das Buchungssystem ungefähr verfügbar sein wird? Ich würde nämlich dann das Buchungssystem nochmal neuaufsetzten, damit ich dann alle Anpassungen der letzten Tage/Wochen automatisch mit abdecken kann....

Vielen Dank und Grüße
Raphael

**Comment by hschiebold** [comment]
Oh ich habe noch gar nicht gesehen, dass Tobias jetzt die 1.8.0 rausgebracht hat, welche zu PHP 8.1 kompatibel ist. Ich hatte schonmal angefangen meine Erweiterungen, was die Türsteuerung angeht und auch für das Payment in eigene Module auszulagern, damit das dann besser migrierbar wird. Das SquareControl Modul ist hier schon fertig. Das Payment Modul aber noch nicht. Größter Knackpunkt wird vermutlich auch das notwendige Update des verwendeten Payum Moduls. Ich schau mal, dass ich das in nächster Zeit mit angehen kann. Eine zeitliche Prognose ist allerdings schwierig. Allerdings muss ich selber mal den server anheben - daher hab ich auch so ein wenig Druck.

**Comment by RaphaelMHa** [comment]
Hallo Holger,
super, vielen Dank für die Rückmeldung. 
Mach dir keinen Stress ;-)

**Comment by gitroli** [comment]
Gibt es schon Fortschritte bezüglich PHP8?

**Comment by RaphaelMHa** [comment]
Hallo Holger, 
hast du evtl. schon News bzgl. PHP 8 Update?

Viele Grüße
Raphael

**Comment by hschiebold** [comment]
Hallo Raphael,

ich hatte leider ein Schei.. Jahr und bin zu nix gekommen. Nunmehr konnte ich mich aber mal einwenig damit beschäftigen. 
Ich habe einen branch https://github.com/hschiebold/ep3-bs/tree/dev_el9_php8 erstellt, in dem ich die aktuellen Anpassungen für die Kompatibilität zu PHP 8.1 mache. 

Ich habe darin meinen bisherigen Stand aus dem master branch mit dem master von Tobias gemerged und ein paar Dateien dann in der Folge aus dem payum, stripe und twig Module erstmal gepatcht,  sodass nach meiner ersten zugegebenermaßen noch kurzen QS Runde keine Fehler, Warnings oder Deprecated Meldungen mehr kamen und der payment workflow sowohl für paypal als auch für stripe wieder funktionierte.     

Die ganzen deprecated Meldungen hätte man theoretisch über die init.php umgehen können, dann kommen sie aber vielleicht beim nächsten PHP Update als Fehler hoch. ( ini_set('error_reporting', E_ALL & ~E_USER_DEPRECATED & ~E_DEPRECATED & ~E_STRICT); )

Die deutlich aufwendigere Lösung, payum, stripe etc. mal zu aktualisieren, muss ich zeitlich vermutlich weiter verschieben. Ich vermute schon dass ich Probleme mit dem alten Payum Module fü rdas Zend framework bekommen werde, da hier die Entwicklung eingestellt ist. 

Tobias hat ja bisher auch nur das alte Zend Framework ein wenig für PHP 8 gepatcht und es wird jetzt in dem src Pfad ausgeliefert. 

Der codestand aus dem hier genannten branch läuft gerade bei mir in einer rocky linux 9 vm mit php 8.1. 

Vielleicht kannst du ja mit testen - man müsste wahrscheinlich nochmal intensiv alle Funktionalitäten insbes. bei den Payment Funktionen durchtesten um an evtl. noch weitern Stellen "vorbei" zu kommen, die noch für PHP 8.1 gepatcht werden müssen. 

Viele Grüße

Holger

**Comment by gitroli** [comment]
Das hört sich ja mal ganz gut an

**Comment by RaphaelMHa** [comment]
Hi Holger,

super! 
Vielen Dank. Ich werde es demnächst testen und berichten.

Grüße
Raphael

**Comment by hschiebold** [comment]
Wenn ihr es testet, dann müsst ihr recht wahrscheinlich auch einmal den autloader aktualisieren, damit Tobias Überschreibungen vom Zend framework in dme src Pfad gewinnen

composer dumpautoload -o

**Comment by RaphaelMHa** [comment]
Hallo Holger,
ich habe es heute mal installiert und ein wenig getestet. Bis jetzt konnte ich noch keine Fehler entdecken :-)
Läuft alles einwandfrei, vielen Dank dafür.

Falls ich noch etwas entdecke, werde ich mich melden.....

Viele Grüße
Raphael

**Comment by hschiebold** [comment]
Auch mit 8.1 getestet oder einer höheren Version?

**Comment by RaphaelMHa** [comment]
Ja, mit 8.1

**Comment by hschiebold** [comment]
Ein Hinweis noch - in der obigen Version müsste schon das refunding einer bereits bezahlten Buchung auf das user budget drin sein.  
Wir lassen ja grundsätzlich eigentlich  keine Stornierung bei uns zu, da wir nicht wollen, dass quasi auf Verdacht im Voraus gebucht und dann wieder storniert wird.
In begründeten Ausnahmefällen (Krankheit, ...) haben wir dann als admin die Buchung storniert und dem Nutzer dann mal als admin als Ausgleich irgendwann eine neue Zeit gebucht. Jetzt bekommt der Nutzer nach einer Stornierung durch den admin das auf sein budget gebucht und kann dann bei der nächsten Buchung aus seinem budget bezahlen.
