### ISSUE TITLE
Mobile Ansicht (Smartphone) statt 2 Tagesanzeige nur 1 Tag

### ISSUE THREAD

**Issue by gitroli** [hschiebold/ep3-bs#18]
Wo finde ich den die Codestelle, dass am Smartphone statt 2 Kalendertagen nur 1 Kalendertag angezeigt wird, mit 3 Plätzen werden sonst die Felder zu klein.
Danke

**Comment by hschiebold** [comment]
Wenn ich mich richtig entsinne, ist das nur eine Frage des css in Bezug auf das responsive design. Da gibt es keine feste Einstellung oder so ähnlich. Schau mal im css nach den width Angaben für die Tagesspalten und änder diese.

**Comment by hschiebold** [comment]
https://github.com/hschiebold/ep3-bs/commit/f3da043b347cb3c6a6bb01d10cfffee03045f1ee

Ich habe mich nochmal mit dem responsive design der app ein wenig befasst und hier meine Anpassungen eingecheckt. Die notwendigen Änderungen, ab wann wieviele Datums Spalten auftauchen habe ich in der default.css ein wenig kommentiert. Je nachdem wieviel Plätze man hat sollte man dort eine andere Staffelung wählen. 

Bisher war das recht hart auf mindestens 2 Datums Spalten bei mir eingestellt. Jetzt ist es wieder etwas flexibler.

**Comment by gitroli** [comment]
das muss ich mir noch ansehen, ich habe es insofern gelöst, dass ich aus einer alten version von tobias einige css übernommen habe
