### ISSUE TITLE
Buchungsbudget bei Stornierung einer Buchung wieder retour erstatten

### ISSUE THREAD

**Issue by gitroli** [hschiebold/ep3-bs#19]
Wenn ein User eine Buchung storniert wird sein Buchungsbudget nicht automatisch wieder um den Betrag erhöht, das ist nicht ausprogrammiert oder?

**Comment by hschiebold** [comment]
Ja vermutlich. Da wir gar keine Stornierung erlauben, ist mir das nicht in den Sinn gekommen. Ich schau mal bei Gelegenheit. Hab nur gerade wenig Zeit, da sehr viel und dringende Arbeit.

**Comment by hschiebold** [comment]
Ich habe jetzt in meinem codestand die cancellation action entsprechend erweitert. Habe noch einige weitere code Änderungen in der selben Klasse, daher muss ich mit dem einchecken noch warten, bis der Rest fertig ist. 
Zusätzlich muss ich hier erwähnen, dass das online payment bisher nicht für Stornierungen ausgelegt ist. Bedeutet - wenn jemand bereits erfolgreich gebucht und online bezahlt hat - wird bei aktvierter Stornierung (wir erlauben dies ja nicht) der bezahlte Betrag nicht irgendwie automatisch zurück erstattet.  Das wäre dann Handarbeit des jeweiligen Verwalters.

**Comment by gitroli** [comment]
Ok und was ist jetzt dann geändert? Wenn vom Buchungsbudget gebucht wird und gecanceled wird, dann wird das Buchungsbudget wider erhöht? Könnte man das beim online Payment bei cancelation nicht einfach beim Buchungsbudget aufladen oder geht das nicht so einfach?

**Comment by hschiebold** [comment]
"Könnte man das beim online Payment bei cancelation nicht einfach beim Buchungsbudget aufladen oder geht das nicht so einfach?"

Uups, daran hab ich noch gar nicht gedacht. Das wäre sicher eine einfache Lösungsmöglichkeit im Zusammenhang mit dem user budget. Sollte auch relativ einfach gehen.

**Comment by hschiebold** [comment]
public function cancellationAction()
    {
        $bid = $this->params()->fromQuery('bid');

        if (! (is_numeric($bid) && $bid > 0)) {
            throw new RuntimeException('This booking does not exist');
        }

        $serviceManager = $this->getServiceLocator();
        $bookingManager = $serviceManager->get('Booking\Manager\BookingManager');
        $bookingBillManager = $serviceManager->get('Booking\Manager\Booking\BillManager');
        $squareValidator = $serviceManager->get('Square\Service\SquareValidator');

        $booking = $bookingManager->get($bid);

        $cancellable = $squareValidator->isCancellable($booking);

        if (! $cancellable) {
            throw new RuntimeException('This booking cannot be cancelled anymore online.');
        }

        $origin = $this->redirectBack()->getOriginAsUrl();

        /* Check cancellation confirmation */

        $confirmed = $this->params()->fromQuery('confirmed');

        if ($confirmed == 'true') {

            $bookingService = $serviceManager->get('Booking\Service\BookingService');

            $userManager = $serviceManager->get('User\Manager\UserManager');
            $user = $userManager->get($booking->get('uid'));

            # redefine user budget if payed with budget
            if ($booking->getMeta('budget')) {
                $user->setMeta('budget', $booking->getMeta('budget'));
                $userManager->save($user);
            }

            # redefine user budget if payed online
            if ($booking->get('status_billing') == 'paid' && $booking->getMeta('directpay') == 'true') {
                $oldbudget = $user->getMeta('budget');
                $bills = $bookingBillManager->getBy(array('bid' => $booking->get('bid')), 'bbid ASC');
                $total = 0;
                if ($bills) {
                    foreach ($bills as $bill) {
                        $total += $bill->need('price');
                    }
                }
                $newbudget = ($oldbudget*100+$total)/100;
                $user->setMeta('budget', $newbudget);
                $userManager->save($user);
            }

            $bookingService->cancelSingle($booking);

            $this->flashMessenger()->addErrorMessage(sprintf($this->t('Your booking has been %scancelled%s.'),
                '<b>', '</b>'));

            return $this->redirectBack()->toOrigin();
        }

        return $this->ajaxViewModel(array(
            'bid' => $bid,
            'origin' => $origin,
        ));
    }

**Comment by hschiebold** [comment]
Mit obiger Erweiterung der cancellationAction sollten beide Fälle erfüllt sein. Einzig bei asynchronen Bezahlmethoden wie SEPA Lastschrift,  bei denen die tatsächliche Bezahlung noch nicht zu dem Zeitpunkt der Stornierung erfolgt ist, würde das budget nicht automatisch  anwachsen.

**Comment by gitroli** [comment]
Super, ich werde es die nächsten Tage mal testen

**Comment by gitroli** [comment]
Mir ist aufgefallen, dass wenn sich ein neuer User registriert, das Buchungsbudget nicht auf 0 gesetzt wird, sondern leer ist, kann das bei der ersten Stornierung ein Problem sein, da es undefined ist. Müsste ich bei jedem User der sich neu registriert das Buchungsbudget manuell auf 0 setzen?

**Comment by hschiebold** [comment]
ich schau mal, ob ich das bei mir in der dev Version testen kann

**Comment by gitroli** [comment]
Die Funktion sieht jetzt bei mir so aus:
`    public function cancellationAction()
    {
        $bid = $this->params()->fromQuery('bid');

            if (! (is_numeric($bid) && $bid > 0)) {
				throw new RuntimeException('This booking does not exist');
			}

    $serviceManager = $this->getServiceLocator();
    $bookingManager = $serviceManager->get('Booking\Manager\BookingManager');
    $bookingBillManager = $serviceManager->get('Booking\Manager\Booking\BillManager');
    $squareValidator = $serviceManager->get('Square\Service\SquareValidator');

    $booking = $bookingManager->get($bid);

    $cancellable = $squareValidator->isCancellable($booking);

    if (! $cancellable) {
        throw new RuntimeException('This booking cannot be cancelled anymore online.');
    }

    $origin = $this->redirectBack()->getOriginAsUrl();

    /* Check cancellation confirmation */

    $confirmed = $this->params()->fromQuery('confirmed');

    if ($confirmed == 'true') {

        $bookingService = $serviceManager->get('Booking\Service\BookingService');

        $userManager = $serviceManager->get('User\Manager\UserManager');
        $user = $userManager->get($booking->get('uid'));

        # redefine user budget if payed with budget
        if ($booking->getMeta('budget')) {
            $user->setMeta('budget', $booking->getMeta('budget'));
            $userManager->save($user);
        }

        # redefine user budget if payed online
        if ($booking->get('status_billing') == 'paid' && $booking->getMeta('directpay') == 'true') {
            $oldbudget = $user->getMeta('budget');
            $bills = $bookingBillManager->getBy(array('bid' => $booking->get('bid')), 'bbid ASC');
            $total = 0;
            if ($bills) {
                foreach ($bills as $bill) {
                    $total += $bill->need('price');
                }
            }
            $newbudget = ($oldbudget*100+$total)/100;
            $user->setMeta('budget', $newbudget);
            $userManager->save($user);
        }

        $bookingService->cancelSingle($booking);

        $this->flashMessenger()->addErrorMessage(sprintf($this->t('Your booking has been %scancelled%s.'),
            '<b>', '</b>'));

        return $this->redirectBack()->toOrigin();
    }

    return $this->ajaxViewModel(array(
        'bid' => $bid,
        'origin' => $origin,
    ));
}`

Bei Stornierung bekomme ich aber nichts aufgeladen? Gibt es außer dem Booking Controller noch wo eine Codestelle?

**Comment by gitroli** [comment]
Ja also ich habe es gerade nochmal getestet, ich habe mit Budget bezahlt, dann storniert, aber Budget wurde nicht wieder erhöht??

**Comment by hschiebold** [comment]
sowiet ich mich auf die Schnelle erinnern kann ist alles in dem BookingController - vergleich mal gegen die aktuelle Version - da solltest du auch sehen wo das "alte" user budget im booking Objekt gespeichert wird - da muss auch ein setMeta('budget') Aufruf sein - da wird nichts wieder "aufgeladen" sondern es wird das "alte" budget wieder gesetzt   

 # redefine user budget if payed with budget
    if ($booking->getMeta('budget')) {
        $user->setMeta('budget', $booking->getMeta('budget'));
        $userManager->save($user);
    }

**Comment by gitroli** [comment]
Dieser Code ist drinnen, das passt. Aber mit es wird das alte Budget gesetzt verstehe ich nicht ganz. Wäre es nicht besser, auf das Budget den Preis dieser Stunde aufzuladen. Von wo nimmt es das "alte" Budget, weil wie oben geschrieben, nach der Stornierung einer Stunde, ist mein Budget das gleiche wie vor der Stornierung und ich hätte angenommen, dass wenn ich storniere ich den Betrag wieder rückerstattet bekomme und sich mein Userbudget dadurch wieder erhöht??

**Comment by gitroli** [comment]
Moment ich muss die ganze bookincontroller.php vergleichen, ev. fehlt mir ein Codeteil noch. Sorry jetzt verstehe ich es ev. moment

**Comment by gitroli** [comment]
Ok jetzt funktioniert es, habe einfach die gesamte bookingcontroller.php genommen, irgendein code teil dürfte noch gefehlt haben. Jetzt wäre nur noch interessant, ob mein oben beschriebenes Problem mit 0 auftreten kann. Vielleicht kann ich es auch irgendwie testen.

**Comment by hschiebold** [comment]
Hab leider grad keine Zeit (muss arbeiten :-( )

Aber damit wir es nicht vergessen - mir kam grad durch deine Beschreibung in den den Sinn, dass da evtl. bei dem zurücksetzen noch ein logischer bug drin ist, wenn sich mehrere Buchungen eines Nutzers zeitlich überschneiden. Nutzer bucht einmal, dann bucht er gleich nochmal und dann storniert er Buchung 1 - es könnte sein, das dann das falsche buget gesetzt wird

**Comment by gitroli** [comment]
Ich würde einfach den Stundenpreis zum Budget addieren, natürlich unter Berücksichtigung ob Vereinsmitglied oder nicht.

**Comment by hschiebold** [comment]
```
# redefine user budget if if status paid
if ($booking->get('status_billing') == 'paid') {
	$bills = $bookingBillManager->getBy(array('bid' => $booking->get('bid')), 'bbid ASC');
	$total = 0;
	if ($bills) {
		foreach ($bills as $bill) {
			$total += $bill->need('price');
		}
	}
 
	$olduserbudget = $user->getMeta('budget');
	if ($olduserbudget == null || $olduserbudget == '') {
		$olduserbudget = 0;
	}

	$newbudget = ($oldbudget*100+$total)/100;

    $user->setMeta('budget', $newbudget);
    $userManager->save($user);
}
```

**Comment by hschiebold** [comment]
das müsste eigentlich die Lösung für beide Probleme sein - muss es noch testen - komm ich erst später dazu

**Comment by hschiebold** [comment]
egal ob mit budget oder online gezahlt wurde wird bei Stornierung der Betrag der Buchung auf das aktuele user budget wieder addiert

**Comment by gitroli** [comment]
irgendwo ist glaube ich noch ein fehler, weil wenn ich Budget habe zB 100 Euro und ich storniere eine Stunde die 18 Euro kostet, ist mein Budget danach 18 Euro, storniere ich dann wieder 1 Stunde die 18 kostet, ist das Budget weiterhin 18 Euro, es scheint als ob das Budget immer 0 gesetzt wird beim stornieren.

**Comment by gitroli** [comment]
es scheint als ob diese Bedingung zutrifft auch wenn der User Budget hat
if ($olduserbudget == null || $olduserbudget == '')

ev passt der leere String nicht??

**Comment by gitroli** [comment]
Ich glaube ich habe den fehler gefunden:
$newbudget = ($oldbudget*100+$total)/100;

Das muss olduserbudget heißen

**Comment by gitroli** [comment]
Bei einem neu registriertem Benutzer existiert das Meta budget noch nicht, darum kann man es auch nicht auf 0 setzen, ich denke man muss beim registriervorgang einbauen, dass das budget Meta mit 0 angelegt wird.

**Comment by gitroli** [comment]
Habe im AccountController.php folgendes eingebaut:
` public function registrationAction()
    {
        $serviceManager = @$this->getServiceLocator();

        $formElementManager = $serviceManager->get('FormElementManager');

        $registrationForm = $formElementManager->get('User\Form\RegistrationForm');

        if ($this->getRequest()->isPost() && $this->option('service.user.registration') == 'true') {
            $registrationForm->setData($this->params()->fromPost());

            if ($registrationForm->isValid()) {
                $registrationData = $registrationForm->getData();

                $meta = array();
                $meta['gender'] = $registrationData['rf-gender'];
				$meta['budget'] = 0;`

**Comment by gitroli** [comment]
meta budget 0 somit ist das Budget für neu registrierte User 0

**Comment by gitroli** [comment]
Ich glaube das im Account Controller brauche ich nicht unbedingt aber es schadet nicht. Aber so passt es jetzt denke ich.

**Comment by gitroli** [comment]
Ich habe alles durchgetestet, es funktioniert. Allerdings einen Bug gibt es der nicht so gut ist und zwar, wenn ich die Buchung storniere, dann dauert ja das manchmal etwas länger, weil es wird im Hintergrund eine SMTP Verbindung zum Mailserver aufgebaut etc. Jetzt ist es möglich während dieser Wartedauer mehrmals auf den Buchung stornieren Button zu drücken und jeder Buttondruck lädt das Userbudget auf. Somit kann sich ein User unrecht Budget aufladen.

**Comment by gitroli** [comment]
Beim Buchen wird das abgefedert weil sofort nach 
Buttondruck der Button ausgegraut wird:

![Bildschirmfoto 2022-10-19 um 21 50 14](https://user-images.githubusercontent.com/31999445/196790188-2e43cb39-57b8-41b7-aee6-9954bf9aebf3.png)

![Bildschirmfoto 2022-10-19 um 21 49 25](https://user-images.githubusercontent.com/31999445/196789963-828683c0-82ca-4bdd-adbd-0149e55f41dc.png)

Hier ist kein mehrmaliges Drücken mehr möglich, das selbe bräuchte ich bei Storno auch ...

**Comment by gitroli** [comment]
Weißt du wie ich das hinbekomme?

**Comment by gitroli** [comment]
Mit folgender Ergänzung in der cancellation.phtml habe ich das Problem behoben:
`        <a href="<?= $this->url('square/booking/cancellation', [], ['query' => ['bid' => $this->bid, 'confirmed' => 'true']]) ?>" class="default-button" id="elementId" onclick="setTimeout(function(){document.getElementById('elementId').removeAttribute('href');}, 1);">
`

**Comment by gitroli** [comment]
Hier wird der href nach Click nach 1ms entfernt

**Comment by hschiebold** [comment]
Das ist sicher ein Hindernis für unbedarfte Nutzer - aber javascript lässt sich auch abschalten etc.
Die Verarbeitung in der cancellation Action müsste wohl zur Sicherheit noch verändert werden.

- zuerst tatsächlich booking canceln
- danach erst user budget  aktualisieren und dabei nochmal checken ob die buchung auch wirklich gecancelt wurde

**Comment by gitroli** [comment]
ja da hast du recht, ich hab mal was auf die schnelle benötigt, weil oft wurde dieser mehrfachbuttondruck auch unabsichtlich ausgeführt, weil es eben manchmal länger dauert

**Comment by gitroli** [comment]
hast du die automatische rückerstattung in Rudolstadt in Betrieb. Hattest du da nie Probleme, mit dem was du hier gemeint hast? 
Nutzer bucht einmal, dann bucht er gleich nochmal und dann storniert er Buchung 1 - es könnte sein, das dann das falsche buget gesetzt wird

**Comment by gitroli** [comment]
Wir haben ja jetzt eine funktionierende Lösung ausgearbeitet, nur ein Security Leak ist noch drinnen ...

**Comment by gitroli** [comment]
Ich habe eine Lösung hiervon genommen:
https://bitcoden.com/answers/disable-href-after-1-click-on-html

Ev wäre den href über css deaktivieren sicherheitstechnisch besser

**Comment by hschiebold** [comment]
> hast du die automatische rückerstattung in Rudolstadt in Betrieb. Hattest du da nie Probleme, mit dem was du hier gemeint hast? Nutzer bucht einmal, dann bucht er gleich nochmal und dann storniert er Buchung 1 - es könnte sein, das dann das falsche buget gesetzt wird

wir lassen gar keine Stornierung zu  - das hatte ich nur schon mal vorbereitet, falls es jemand braucht ;-)

**Comment by hschiebold** [comment]
Habe meine Anpassungen basierend auf diesem Ticket jetzt mal gemacht kurz getestet und eingescheckt. Teile von dir hab ich übernommen. Danke.

https://github.com/hschiebold/ep3-bs/commit/7c65a09cf9e3115d207cadeff0834f10af7b8684

Habe auch noch das refunding eingeführt, wenn man als Admin per backend eine bezahlte Buchung storniert.

**Comment by gitroli** [comment]
![image](https://user-images.githubusercontent.com/31999445/197026816-08b4c114-db22-431d-b9af-42e16553015f.png)
setMeta im AccountController passt nicht, ich glaube das musst du so wie ich machen

**Comment by hschiebold** [comment]
uups das war natürlich großer Unfug - und natürlich hab ich das registrieren nicht extra getestet - Schei.. copy paste

sorry - habs korrigiert

**Comment by gitroli** [comment]
Ist es auch möglich dass ein aktivierter Benutzer eine Stunde seines eigenen Abos storniert? Ist das irgendwo vorgesehen oder wo könnte ich ansetzen um das möglich zu machen? Weiß gar nicht ob das in der Version von Tobias überhaupt geht?

**Comment by hschiebold** [comment]
Ich glaube nicht. Als Admin ja - aber als Nutzer selber glaub ich nicht. Auch wenn der Admin das macht ist das eine andere Funktionalität als die Stornierung einer Einzelbuchung. Ein refunding findet dabei bisher auch nicht statt.

**Comment by gitroli** [comment]
Ich habe gerade ein Abo manuell als admin auf bezahlt gesetzt, da kommt dieser Fehler:
![image](https://user-images.githubusercontent.com/31999445/197381250-92cae452-5502-4147-b752-1b6a28b40edb.png)
Ich glaube das hat mit deiner letzten Änderung zu tun dass bei Admin Stornierungen der Betrag auch rückerstattet wird. Kannst du das mal checken.

**Comment by hschiebold** [comment]
kommst du noch an den stacktrace ran?

**Comment by hschiebold** [comment]
muss schon länger drin sein - hängt mit der Türcodeaktualisierung zusammen 

Zeile 156 stand bei mir im stacktrace vom backend BookingController - muss auf $savedBooking statt auf $booking referenzieren, da $booking zu diesem Zeitpunkt / Umstand null ist 

 $square = $squareManager->get($savedBooking->get('sid'));

**Comment by gitroli** [comment]
danke funktioniert nun

**Comment by gitroli** [comment]
diesen thread schließe ich jetzt auch, dass funktioniert ja jetzt
