### ISSUE TITLE
Aktive Buchungen einschränken

### ISSUE THREAD

**Issue by gitroli** [hschiebold/ep3-bs#2]
Hi, wäre es möglich diese commits in deinen fork zu übernehmen, Bzw wichtig wäre mir dieser wo man angeben kann, wieviele aktive Buchungen ein User haben darf und wenn das Limit erreicht ist, er warten muss bis er die Stunden gespielt hat oder storniert.

**Comment by gitroli** [comment]
https://github.com/tkrebs/ep3-bs/issues/266#issuecomment-617124548

**Comment by gitroli** [comment]
Fast zum Schluss im issue sind die commits verlinkt

**Comment by hschiebold** [comment]
Ich schau es mir an die Tage - bekomm ich bestimmt hin - ich schau gleich mal ob da noch mehr entstanden ist in der Zwischenzeit

**Comment by gitroli** [comment]
Danke

**Comment by gitroli** [comment]
Bist du schon dazu gekommen?

**Comment by hschiebold** [comment]
Sorry noch nicht. Zu viel Homeoffice 😉 ich hoffe ich komm diese Woche dazu.

**Comment by hschiebold** [comment]
Ich hab gerade mit der 1.6.4 von tkrebs gemerged. Habe allerdings selber noch nicht wirklich getestet.

**Comment by hschiebold** [comment]
können wir den issue schließen?

**Comment by gitroli** [comment]
ja danke
