### ISSUE TITLE
Verbunde Kalenderzellen falsche Zeitanzeige

### ISSUE THREAD

**Issue by gitroli** [hschiebold/ep3-bs#21]
Wenn mehr als 1 Stunde gebucht ist, und die Zellen im Kalender verbunden werden, wird immer nur 1 Stunde als belegt angezeigt.
![Bildschirmfoto 2022-10-02 um 09 12 33](https://user-images.githubusercontent.com/31999445/193451803-c2b57e59-256d-45c7-9abb-4766af1aac2b.png)
![Bildschirmfoto 2022-10-02 um 09 12 47](https://user-images.githubusercontent.com/31999445/193451808-5f36412d-d08e-4d38-b2e4-bdc97eaf3e6a.png)

**Comment by hschiebold** [comment]
https://github.com/hschiebold/ep3-bs/commit/47caa828f1126b50e2c89ac3f6cd33170f35b990

korrigiert in der index.js - index.min.js muss noch mit minifier aktualisiert werden

**Comment by gitroli** [comment]
super danke dir
