### ISSUE TITLE
iFrame Einbindung Reservierungssystem in Homepage

### ISSUE THREAD

**Issue by gitroli** [hschiebold/ep3-bs#22]
Ich bin gerade am Diskutieren mit dem Webdesigner unserer Homepage, wieso er das Reservierungssystem in einem neuen Fenster aufmachen soll und nicht als iFrame einbinden.  So habt ihr das ja auch bei tennis-rudolstadt.de gemacht. Könntest du mir ev. Gründe nennen wieso ihr es auch in einem neuen Fenster öffnet: App-Funktionalität, ev Probleme beim Payment Virenscanner schlagen an? Die Argumentation vom Webdesigner ist dass die Homepage uninteressant wird und die Leute gleich direkt auf Reservierungssystem gehen und ev andere Infos von der Homepage untergehen, wo ich ihm auch Recht gebe. Danke für die Antwort

**Comment by gitroli** [comment]
Ev Umstellung Basic Auth auf OAuth in einem späteren Release, dann gibts wahrscheinlich auch Probleme mit iFrame?

**Comment by hschiebold** [comment]
Hauptsächlich wegen der pwa Funktionalität als App

Hab es auch funktional nie in einem iFrame getestet (payment, tokens, auth, webhook ...)

Bin selber überhaupt kein Freund von iFrame 

Die Website selber ist aus der App wieder an x Stellen verlinkt

**Comment by gitroli** [comment]
ok danke
