### ISSUE TITLE
Buchungsbestätigungsmail wird 2x versendet

### ISSUE THREAD

**Issue by gitroli** [hschiebold/ep3-bs#23]
Wenn ich als Benutzer einen Platz buche bekomme ich das Bestätigungsmail immer 2 mal. Liegt das an meiner Mailkonfiguration oder ist im Code noch was hinterlegt? Wobei bei der Mailkonfig ist ja auch keine solche Option?

**Comment by gitroli** [comment]
Ich habe jetzt im Mailverlauf nochmal nachgesehen, manchmal wird es nur 1x gesendet, aber das kommt selten vor. Kann es sein wenn der SMTP Server länger braucht zum Antworten, dass dann noch ein Mail generiert wird?

**Comment by gitroli** [comment]
Ich habe noch einige Tests gemacht, also bei Cancel (wenn ein User storniert), bekommt er nur ein Mail, nur wenn er bucht 2 Mails.

**Comment by hschiebold** [comment]
Passiert das bei allen Zahlungs / Buchungsarten oder nur bei einer ? Also bspw. Per Paypal oder per Budget ...

**Comment by gitroli** [comment]
Bei User Budget und Paypal werden 2 Mails gesendet, bei Stripe (Card und Sepa) nur 1 Mail

**Comment by gitroli** [comment]
Habe mich getäuscht habe nun auch eine SEPA Zahlung gefunden wo 2 Bestätigungsmail gesendet wurden, kann also keine Logik dahinter fest machen

**Comment by hschiebold** [comment]
Ich schau mal die Woche - Wetter zu schön heute

**Comment by gitroli** [comment]
Folgendes habe ich gerade noch getestet, ich habe mal die Preise rausgenommen auf einem Platz, so dass dieser nichts kostet, dann bekommt man bei der Buchung auch nur 1 Bestätigungsmail, also es muss irgendwie mit der Zahlung zusammen hängen.

**Comment by hschiebold** [comment]
Sind die 2 Mails an irgendeiner Stelle unterschiedlich?

**Comment by gitroli** [comment]
nein komplett identisch

**Comment by hschiebold** [comment]
ich kann das Problem nun wenigstens nachstellen, aber nur bei Bezahlung per budget - da bekomme ich tatsächlich beide mails ( die für den Verwalter und den Kunden - beides geht auf eine mail Adresse bei mir ) 2 x - also insgesamt 4

in der "doppelten" ist dann zusätzlich die booking notice enthalten:
 Anmerkungen:
 payment with user budget

da wird evtl. irgendwo das Problem liegen

NUR - bei den anderen Bezahlmethoden passiert das bei mir nicht - ich habe meinen smtp allerdings auch lokal auf dem gleichen server - wie ist das bei dir?

**Comment by gitroli** [comment]
Verwende Gmail smtp Server

**Comment by gitroli** [comment]
Ja also bei User Budget definitiv, ich kann nochmal nachkontrollieren, ev hab ich mich verschaut bei den anderen Zahlungsmethoden

**Comment by hschiebold** [comment]
https://github.com/hschiebold/ep3-bs/commit/a3a5d9620de860378ab96b6301653b76cdf7d50c

updatePaymentSingle triggert den event create.single nochmal, der die mail sendet

**Comment by gitroli** [comment]
Top probiere ich morgen dann gleich, jetzt ist schon zu spät

**Comment by gitroli** [comment]
Funktioniert, nur mehr 1 Mail wird jetzt gesendet, danke
