### ISSUE TITLE
PHP 8 SUPPORT

### ISSUE THREAD

**Issue by gitroli** [hschiebold/ep3-bs#24]
Hallo Holger,

ich bin sehr zufrieden mit dem System und habe es voll in Loxone integriert mit Licht und Zutritt.
Auch bezahlt wird darüber in unserer Halle.

Leider sitzt mir mein Webhoster im Nacken und möchte den Support für die benötigte PHP7 Version bald abdrehen.
Ich muss für die nächste Hallensaison planen und wollte mal nachfragen, ob du irgendwann mal das Upgrade auf PHP8 angehst?

Ansonsten muss ich leider mit Tränen nach Alternativen suchen.

Beste Grüße

**Comment by hschiebold** [comment]
siehe #16
