### ISSUE TITLE
IBAN - Meine Daten

### ISSUE THREAD

**Issue by gitroli** [hschiebold/ep3-bs#27]
Unter meine Daten kann ja die IBAN hinterlegt werden:
![image](https://github.com/user-attachments/assets/eafae21f-60a1-4c41-8f5d-cd63ed0f4a90)

Das habe ich mal ausprobiert.
Beim Bezahlen, wenn man Lastschrift auswählt wird aber noch nichts automatisch ausgefüllt.

Hat das derzeit schon eine Funktion, wenn man den IBAN unter meine Daten hinterlegt oder gehört das noch programmiert.

**Comment by hschiebold** [comment]
Ja das hatte ich gehofft, die IBAN vorausfüllen zu können und hatte schon das user Formular dafür erweitert. Aber der payment Prozess von stripe lässt das aus Sicherheitsgründen gar nicht zu, die IBAN "von aussen" zu übergeben.  

Man müsste eigentlich das IBAN Feld aus dem user form wieder entfernen. Es sei denn es kann auch für andere Dinge wie manuelle Abo's etc. genutzt werden, dann halt nur den Beschreibungstext ändern.

**Comment by gitroli** [comment]
Ok alles klar, danke
