### ISSUE TITLE
Route with name "?" not found**

### ISSUE THREAD

**Issue by murreni** [hschiebold/ep3-bs#3]
Hallo,

ich versuche gerade die Zahlungsfunktion zu testen.
local.php habe ich um die entsprechenden Login daten erweitert. Wenn ich allerdings eine zahlung vornehmen will erscheint folgende Fehlermeldung:
**Oops ... da ist wohl etwas schief gelaufen
Route with name "?" not found**

habe ich etwas übersehen?

**Comment by hschiebold** [comment]
Bestimmt 😉 poste mal deine local (sensible Infos bereinigt)

**Comment by murreni** [comment]
ich hatte vergessen in der Project.php baseurl und proxyurl nachzutragen.
jetzt erscheint aber folgende Meldung:
Oops ... da ist wohl etwas schief gelaufen
A token with hash `215-EBbrOcb0wi0VjeQ4gMqUtRaNyMUs9qANiLZtdlY` could not be found.

**Comment by murreni** [comment]
ich glaub ich habs gefunden. 
hab die rechte für data/payum auf 777 gestellt und nun gehts :-)

**Comment by hschiebold** [comment]
sorry aber 777 ist NIEMALS eine gute Idee - schon gar nicht für den data Bereich eines Bezahlsystems

 und ja der user unter dem die app auf deinem server läuft benötigt Schreibrechte in diesem Bereich

**Comment by murreni** [comment]
Danke für die Info.
Kannst du mir auch sagen wie ich die entsprechenden schreibrechte für den user pi setzen kann?
ich bekomme es irgendwie nicht hin. es erscheint wieder die token fehlermeldung.....

**Comment by murreni** [comment]
hat geklappt. danke
