### ISSUE TITLE
Linkout

### ISSUE THREAD

**Issue by murreni** [hschiebold/ep3-bs#4]
Hallo,

den Paypal- Bezahlvorgang kann ich nun starten und die Transaktion durchführen. 
Allerdings routet er mich dannach auf folgenden link:

http://192.168.178.54/**tvas-booking-dev**/public/square/booking/payment/done?payum_token=

wie kann ich das "tvas-booking-dev" ändern/wegbekommen?

Danke und Gruß

**Comment by hschiebold** [comment]
Hast du noch die instance Variable in der project.php auf tvas-booking-dev ? Die wird dann dort standardmäßig bei mir von basepath und als cookie prefix benutzt.

**Comment by hschiebold** [comment]
Ich hab mehrere Instanzen auf dem selben server (dev / prod ...) - Um die sauber zu trennen ...

**Comment by murreni** [comment]
Ahh. Danke :-)
