### ISSUE TITLE
Hintergrundfarbe ändern

### ISSUE THREAD

**Issue by murreni** [hschiebold/ep3-bs#5]
Hi,
kannst du mir sagen wie ich den Hintergrund ändern kann?
bg.jpg austauschen klappt bei deinem Fork nicht. Was muss ich da ändern?

Danke und Gruß

**Comment by hschiebold** [comment]
in puplic/css-client ist meine project css (tennis-rudolstadt.css)

**Comment by murreni** [comment]
Danke :-)
