### ISSUE TITLE
Fehler bei Buchung

### ISSUE THREAD

**Issue by murreni** [hschiebold/ep3-bs#6]
Sobald ich als User auf buchen klicke erscheint das:

**Javascript muss in ihrem Webbrowser aktiviert sein um fortzufahren. Im Zweifelsfall benutzen sie einfach einen anderen Webbrowser (z.B. Mozilla Firefox)**

Wenn ich als Admin eine Buchung vornehme klappt es!

Irgendeine Idee?

**Comment by hschiebold** [comment]
Diese Fehlermeldung wir scheinbar nur von dem square/booking/customization modul heraus gegeben. (grep nach "Zweifelsfall") Das ist das modul über welches man Produkte hinzubuchen kann zum Platz. Dies greift denk ich nur denk ich auch nur bei der Buchung als user. Als admin hat man da schon eine ganz andere Sicht. das gehört alles zum Standard ep3bs - da war ich nicht dran -glaube ich. Scheinbar greift die Prüfung auf javascript dann bei dir. Ist denn ajavascript auchwirklich aktiv? Hast du mal das Netzwerkpanel / Konsole deiens Browsers kontrolliert? Irgendwelche Fehler dort zusehen?

**Comment by hschiebold** [comment]
Bei mir tritt das natürlich nicht auf ;-) Hab extra mal meiner dev Instanz ein "Produkt" verpasst.

**Comment by hschiebold** [comment]
keine weitere Meldung - issue wird geschlossen
