### ISSUE TITLE
Fehler bei Offline Installation (WAMP)

### ISSUE THREAD

**Issue by wxx13** [hschiebold/ep3-bs#8]
Hallo ,
habe versucht ep3-master offline auf meinem PC zu installieren.Sofern ich die Seite starten will ersachein folgende fehlermeldung:
 Fatal error: Uncaught Error: Class 'Payum\Stripe\KlarnaCheckoutGatewayFactory' not found in C:\Apache\www\ep3master\config\autoload\local.php on line 71
Zeile 71='klarna_checkout' => (new \Payum\Stripe\KlarnaCheckoutGatewayFactory())->create(array(
                'secret' => '?',
                'merchant_id' => '?',
                'sandbox' => true

Bitte um Hilfe
Danke klaus

**Comment by hschiebold** [comment]
Dir fehlt das Payum Modul im Vendor Pfad. Ich hatte in der Readme beschrieben, das ich meine kompletten Vendor Pfad mit den zusätzlichen Modulen, Anpassungen eingecheckt habe. Den musst du verwenden oder die Module da raus holen. 

Gruß Holger

**Comment by wxx13** [comment]
Hallo Holger,
komme leider erst heute  zum Antworten. Habe noch mal alles gelesen und es funktioniert jetzt.
Danke nochmals, kannst das Issue schließen.
Gruß klaus
