### ISSUE TITLE
User\Form\EditIbanForm was not found

### ISSUE THREAD

**Issue by wes45** [hschiebold/ep3-bs#9]
Hi there,
If I click My account as user and as admin, I get this zend error below. Would someone know how this can be fixed? Thanks and regards

Exception details

Type
    Zend\Form\Exception\InvalidElementException

Message
    A plugin by the name "User\Form\EditIbanForm" was not found in the plugin manager Zend\Form\FormElementManager\FormElementManagerV2Polyfill

File
/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerTrait.php:41

**Comment by hschiebold** [comment]
Sorry i tried to build a function to save the IBAN for SEPA DEBIT via payum but did not finished it yet and forgot to check in this form. It is now in /module/User/src/User/Form

**Comment by wes45** [comment]
Hi Holger,
Thank you very much for helping, that is really great of you. The missing file was indeed the problem.
I am trying to get your ep3-bs version to work with payment system stripe, thanks and regards, Wes

**Comment by wes45** [comment]
When booking a court, payment selection shows OK, when I select Stripe and click "go to payment" this error below shows. Could you please advice? 

Exception details

Type
    Twig\Error\LoaderError

Message
    Template "@PayumStripe/Action/stripe_js.html.twig" is not defined.

File
    /vendor/twig/twig/src/Loader/ChainLoader.php:98

Stack trace
/vendor/twig/twig/src/Environment.php(299): Twig\Loader\ChainLoader->getCacheKey('@PayumStripe/Ac...')
/vendor/twig/twig/src/Environment.php(381): Twig\Environment->getTemplateClass('@PayumStripe/Ac...')
/vendor/twig/twig/src/Environment.php(359): Twig\Environment->loadTemplate('@PayumStripe/Ac...')
...

**Comment by hschiebold** [comment]
Do you have the vendor path from my instance here? Ther must be the path  vendor/payum/stripe/Payum/Stripe/Resources/views/Action/ with the twig templates in it.

**Comment by wes45** [comment]
yes, I have 7 .twig files in
/vendor/payum/stripe/Payum/Stripe/Resources/views/Action
including stripe_js.html.twig

**Comment by wes45** [comment]
I am trying to update with composer now, maybe something missed out

**Comment by wes45** [comment]
I also tested with selecting PayPal, but then I get "Oops ... something went wrong here. This page does not (yet) exist" error.
So everything works OK, until I click "go to payment" after selecting PayPal or Stripe as payment.
Would you have any clue what I did wrong ?

**Comment by hschiebold** [comment]
At the moment I have not really an idea. There are a few guys using my fork as I know. Do you have the configs like in my fork?

**Comment by wes45** [comment]
Probably my mistake is that I did not yet "extend" the twig templates in the new language I added. Could you please explain a bit more how I have to do this? In your instruction you write:

Stripe payment site
can be changed via the twig templates of payumStripe - for other language support than German and English you have to extend these templates too
vendor/payum/stripe/Payum/Stripe/Resources/views/Action/stripe_js.html.twig

Could you please advice how to do this for a new added language? Thanks and regards, Wes

**Comment by hschiebold** [comment]
there is something wrong with the payum module in your instance - when paypal isn't working too

please have a look of all config scripts and compare these with mine

**Comment by hschiebold** [comment]
{{ model.metadata.locale == 'de-DE' ? 'Kreditkarte' : 'Card' }}

you fill find such code in the twig template - default is english and the only other language in the template is german at the moment 

this code has to b extended for the next language or you replace the german part with yours

**Comment by wes45** [comment]
I deleted everything, started all over by doing a git pull from this repository, did not change language, left everything the same. 
But the paypal page is not found. Ran composer once more, but still no paypal. I have no clue what goes wrong, very frustrating.
Composer shows these modules installed as shown below. Does anyone know what could be wrong? Thanks and regards, Wes
![20200827composerstatus](https://user-images.githubusercontent.com/7498683/91454581-6f108400-e881-11ea-8338-e352095fa04c.png)

**Comment by wes45** [comment]
it goes wrong with Stripe too, after entering IBAN and clicking next, this url does not load and gives an error:
public/square/booking/payment/confirm?payum_token=EHfNOFZWwAMFOfdjFGRgSktX7Id8oc6rah8W45mG8lo

for PayPal it is the same problem, this url does not load and gives an error:
/public/square/booking/payment/done?payum_token=9Akyctv8vU-h5MMFvlFtt39U4DERjpU-qos4VKCt8tk

Does anyone have a clue? thanks and regards

**Comment by hschiebold** [comment]
after git pull - did you edit the configs? could you post your configs?

yesterday another guy reported using successfully this fork - so it should work normally

**Comment by hschiebold** [comment]
the routes to public/square/booking/payment/confirm are defined in module/Square/config/module.config.php

do they exist there?

**Comment by hschiebold** [comment]
i have just tested the deployment from this fork on my machine where i have the basics mysql, httpd, php 7.2 

git clone https://github.com/hschiebold/ep3-bs in a new directory
chown apache:apache for the data and public dir (the httpd user) - the payum tokens are written to the data dir for example
copied my local.php and project.php from my other instance / dir with all the payum related entries and the database connection 

and all is working

**Comment by wes45** [comment]
Hi Holger,
Thank you for helping. You write php7.2 , I use 7.3 as it says php7+ .
Maybe that is the problem? I will downgrade to 7.2
The routes are in module/Square/config/module.config.php


thanks and regards,
Wes

Op vr 28 aug. 2020 om 11:40 schreef hschiebold <notifications@github.com>:

**Comment by wes45** [comment]
In the data folder there are payum files like
payum-model-UXPmN2J_nQE6CJFu-xeCRsPMGQQifvbjpdaCqfosCDs in the data/payum/
folder
but no token files. Should the token files be in that folder too?

**Comment by hschiebold** [comment]
Yes as tkrebs in the original project wrote ep3bs is not yet compatible with 7.3+ because it depends on ZendFramework - but the errors you describing are not related to this Problem

I think somehow the routes to the payum endpoints are not defined in your instance. 

Did you edit the configs according to mine?

**Comment by wes45** [comment]
the website is in httpdocs/
the server is set to point to httpdocs/public

the configs in /httpdocs/config/autoload are:

PROJECT.PHP

<?php
/**
 * project application configuration
 *
 */


$instance = '';

return array(
    // basepath of the instance on your server - i.e. tvas-booking-dev for
https://tennis-rudolstadt.de/tvas-booking-dev or '' if you don't have a
basepath before public/
    'basepath' => $instance,
    // origin url of your server - http://yourip - if  you don't have a
proxy, baseurl and proxyurl should be the same like
https://tennis-rudolstadt.de
    'baseurl' => 'https://banenreserveren.nl',
    // the proxy url - i.e. https://tennis-rudolstadt.de
    'proxyurl' => 'https://banenreserveren.nl',
    'cookie_config' => array(
        'cookie_name_prefix' => $instance,
    ),
    'redirect_config' => array(
        'cookie_name' => $instance.'-origin',
        'default_origin' => 'frontend',
    ),
    'session_config' => array(
        'name' => $instance.'-session',
        'save_path' => getcwd() . '/data/session/',
        'use_cookies' => true,
        'use_only_cookies' => true,
    ),
    'genDoorCode' => false,
    'doorCodeTimeBuffer' => '15 minutes',
    // API http request for your door system
    'doorCodeRequest' => '?',
    // show a flash message where you can manually book if you disable all
payment methods
    'tmpBookingAt' => '?',
    // enable/disable specific payment providers
    'paypal' => true,
    'stripe' => true,
    // enable/disable additional stripe payment methods like sepa_debit
    'stripePaymentMethods' => array(
        'ideal',
'card',
        'sepa_debit'
    ),
    // not yet implemented
    'klarna' => false,
    // classic behaviour of ep3-bs with booking on bill
    'billing' => false,
);


LOCAL.PHP

<?php
/**
 * Local application configuration
 *
 * Insert your local database credentials here
 * and provide the email address the system should use.
 */

$detailsClass = 'Application\Model\PaymentDetails';

$project_config = require 'config/autoload/project.php';

return array_merge($project_config, array(
    'db' => array(
        'database' => '********',
        'username' => '*******',
        'password' => '********',

        'hostname' => 'localhost',
        'port' => null,
    ),
    'mail' => array(
        'type' => 'sendmail', // or 'smtp' or 'smtp-tls'
        'address' => 'info@banenreserveren.nl',
            // Make sure 'bookings.example.com' matches the hosting domain
when using type 'sendmail'

        'host' => '?', // for 'smtp' type only, otherwise remove or leave
as is
        'user' => '?', // for 'smtp' type only, otherwise remove or leave
as is
        'pw' => '?', // for 'smtp' type only, otherwise remove or leave as
is

        'port' => 'auto', // for 'smtp' type only, otherwise remove or
leave as is
        'auth' => 'plain', // for 'smtp' type only, change this to 'login'
if you have problems with SMTP authentication
    ),
    'i18n' => array(
        'choice' => array(
            'en-US' => 'English',
            'de-DE' => 'Deutsch',

            // More possible languages:
            // 'fr-FR' => 'Français',
            // 'hu-HU' => 'Magyar',
        ),

        'currency' => 'EUR',

        // The language is usually detected from the user's web browser.
        // If it cannot be detected automatically and there is no cookie
from a manual language selection,
        // the following locale will be used as the default "fallback":
        'locale' => 'de-DE',
    ),
    'payum' => array(
        'token_storage' => new \Payum\Core\Storage\FilesystemStorage(
            __DIR__.'/../../data/payum',
            'Application\Model\PaymentSecurityToken',
            'hash'
        ),
        'gateways' => array(
            'paypal_ec' => (new
\Payum\Paypal\ExpressCheckout\Nvp\PaypalExpressCheckoutGatewayFactory())->create(array(
                'username' => '**********l',
                'password' =>
'********YUgxbnuGIakIT-I_rUaLlcMVNy0z9EGQ3ldtAzZntex-sLpVPUZ0x3RYP4rA-JuziR',
                'signature' =>
'********2aCMHl-pTudPY_a9UujeEAQrlz8z3mS8nOTLMppcCqhoXHzLkz4K8Fap0QBCHVeQozy_',
                'sandbox' => true
            )),
            'stripe' => (new
\Payum\Stripe\StripeCheckoutGatewayFactory())->create(array(
                'publishable_key' =>
'pk_test_******rM8lpKsVWHQ3zVy7fN8bcgA9okF9QxZyI36nqQ8jOtcI0IiVp7xgmoea4tD3pBlqaIYmop6ZrxNC4LQs00poxUxZvj',
                'secret_key' =>
'sk_test_*******L3rM8lpKsV2MrrMTehic0swrlSFmMOZLFrC5OXWDFUTaMErhsnUASDXVlXU1gZOl0R2dg9BMCzBuXPuLrZ00YPnO2EuS',
                'sca_flow' => true,
                'payum.template.obtain_token' =>
'@PayumStripe/Action/stripe_js.html.twig',
                'payum.template.require_confirmation' =>
'@PayumStripe/Action/stripe_confirm.html.twig'
            )),

        ),
        'storages' => array(
            $detailsClass => new
\Payum\Core\Storage\FilesystemStorage(__DIR__.'/../../data/payum',
$detailsClass, 'id'),
        )
    ),
));

**Comment by hschiebold** [comment]
the website is in httpdocs/
the server is set to point to httpdocs/public


somewher her is the problem 

the route https://banenreserveren.nl/public/square/booking/payment/done? does not exist

only without public in your instance

https://banenreserveren.nl/square/booking/payment/done

**Comment by hschiebold** [comment]
why did you set "the server is set to point to httpdocs/public" ? 

can you try to set httpdocs ?

**Comment by hschiebold** [comment]
the problem in your instance with root to httpdocs/public lies in these 3 lines in the BookingController with a bit hardcoded (sorry for that :-( ) reference to the route with /public/square/booking/payment 

/public/square/booking/payment/...

**Comment by hschiebold** [comment]
module/Square/src/Square/Controller/BookingController.php

**Comment by hschiebold** [comment]
and in the twig templates there are routes too to /public/square

**Comment by hschiebold** [comment]
"why did you set "the server is set to point to httpdocs/public" ?"

hmm it seems that nobody using this fork including me followed the last instructions in the docs/install.txt :-(

i will change the config, the BookingController and the twig template so it is possible to follow the instruction like you did obviosly

**Comment by wes45** [comment]
yes, the security was the reason;

--- Deployment ---

Once you are satisfied with the system and want to use it in the wild,
please make sure to set the Apache document root directly to the
/public/-directory
so that your domain will read like that:

http://example.com/

And not like that:

http://example.com/public/

The latter is a huge security threat, that is only acceptable while testing
the system.

Op vr 28 aug. 2020 om 14:49 schreef hschiebold <notifications@github.com>:

**Comment by wes45** [comment]
Thank you very much for helping Holger, and luckily it is also better for
your own website and those of other users to take out the /public part out
of the url
Thanks and regards, Wes

**Comment by hschiebold** [comment]
just pushed the mod - can you test without the public?

**Comment by wes45** [comment]
did git pull, running website without public, stripe works OK, PayPal gives error

**Comment by wes45** [comment]
"fehler wehrend bezalvorgang" is the paypal error

**Comment by hschiebold** [comment]
ok i will have a look at the paypal error

ideal payment via stripe is not implemented yet - only card and sepa debit - but can be extended maybe -

**Comment by hschiebold** [comment]
hmm there i see no communication to paypal at all from your site - the paypal sandbox credentials in the config are ok?

**Comment by wes45** [comment]
maybe I mixed things up? paypal shows

account
client-ID
secret

in local .php I set

username = account
password =  client-ID 
signature = secret

but maybe has to be:

username = account
password =  secret
signature = client-ID

**Comment by wes45** [comment]
I tested with 
username = account
password = secret
signature = client-ID
but paypal gives the same error

**Comment by hschiebold** [comment]
it isn't client and secret - that is another type of account

its password and signature

**Comment by hschiebold** [comment]
there is something like facilitator_api1 in the username integrated

**Comment by hschiebold** [comment]
look for NVP/SOAP API credentials

if i'm log in in sandbox.paypal.com with *facilitator* account then under https://www.sandbox.paypal.com/businessprofile/mytools/apiaccess/firstparty/signature

**Comment by wes45** [comment]
you are totally right, I was creating the sandbox credentials in the paypal app developers area,
now I created them in the default paypal area and it is working A-OK,
thank you very much for your great help and advice!

**Comment by wes45** [comment]
switching to test live now, would you know what this stripe setting in local.php is for? Does it stay true or needs to switch to false for live testing?

'sca_flow' => true,

**Comment by hschiebold** [comment]
SCA is for StrongCustomerAuthentication workflow - you can test the sca flow with special test card numbers from stripe

**Comment by wes45** [comment]
Hi holger,Was it you who emailed me from a gmail account? I replied to you today several times with access codes and a gift,, but am a bit worried  it wasn't you. Hope to hear it is ok, thanks,Wes

**Comment by hschiebold** [comment]
I got your emails. It is a German Provider gmx. So thank you. And thank you too. The problem with public was my fault and this helps me and maybe others too.

**Comment by wes45** [comment]
If one day you would have some time available to see if activating the payment-option "ideal" in Stripe is doable without consuming too much of your time, that would be great. I don't know if you have ideal in Germany too, but here in NL it is the number 1 online payment method. Thanks for all your help and best regards, wes

**Comment by hschiebold** [comment]
It could be possible. Stripe has few APIs and I’m using the PaymentIntent API as I know. With a short look ideal should be possible with this API. I will have a deeper look on a rainy day.

**Comment by wes45** [comment]
That would be great, thank you very much!

**Comment by hschiebold** [comment]
Hi Wessel, 

can we close the isuue?

**Comment by wes45** [comment]
Hi Holger,

Yes, as far as I can tell, it works A-OK. Thank you very much for building
this. 

Thanks and regards,
Wessel

Op do 8 okt. 2020 om 11:28 schreef hschiebold <notifications@github.com>:
